// Writes migrations/0002_seed.sql from seed-data.ts, using the same SQL the Worker uses.
// Run with: node scripts/build-seed.ts
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { collectionSchemas, formatIssues, settingsSchemas } from '../src/shared/schema.ts'
import { collectionStatements, settingStatement, type Statement } from '../worker/db.ts'
import { seed } from './seed-data.ts'

// Validate first, so the database never starts with content the admin would reject.
for (const [key, schema] of Object.entries(settingsSchemas)) {
  const result = schema.safeParse(seed.settings[key as keyof typeof settingsSchemas])
  if (!result.success) throw new Error(`settings.${key}:\n${formatIssues(result.error)}`)
}
for (const [key, schema] of Object.entries(collectionSchemas)) {
  const result = schema.safeParse(seed[key as keyof typeof collectionSchemas])
  if (!result.success) throw new Error(`${key}:\n${formatIssues(result.error)}`)
}

const literal = (value: string | number) =>
  typeof value === 'number' ? String(value) : `'${value.replaceAll("'", "''")}'`

// Swap each ? placeholder for its value as a SQL literal.
const toSql = ({ sql, params }: Statement) => {
  let i = 0
  return sql.replace(/\s+/g, ' ').replace(/\?/g, () => literal(params[i++])) + ';'
}

const statements = [
  ...Object.entries(seed.settings).map(([key, value]) =>
    settingStatement(key as keyof typeof seed.settings, value as never),
  ),
  // Skip the DELETE that collectionStatements starts with: the tables are new and empty.
  ...collectionStatements('projects', seed.projects).slice(1),
  ...collectionStatements('experience', seed.experience).slice(1),
  ...collectionStatements('themes', seed.themes).slice(1),
]

const output = [
  '-- Generated by scripts/build-seed.ts from scripts/seed-data.ts. Do not edit by hand.',
  '-- Fills the database with the site content from before the admin dashboard existed.',
  ...statements.map(toSql),
  '',
].join('\n')

writeFileSync(join(import.meta.dirname, '../migrations/0002_seed.sql'), output)
console.log(`Wrote migrations/0002_seed.sql (${statements.length} statements)`)
